version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/databases/dark_data.db
    depends_on:
      - redis
    restart: unless-stopped

  mcp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python -m dark_data.mcp.servers.mcp_server
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - DATABASE_PATH=/app/data/databases/dark_data.db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped

volumes:
  redis_data: